---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: montage-ai-ingress
  namespace: montage-ai
  labels:
    app: montage-ai
  annotations:
    traefik.ingress.kubernetes.io/router.entrypoints: web
spec:
  ingressClassName: traefik
  rules:
  - host: <MONTAGE_HOSTNAME>
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: montage-ai-web
            port:
              number: 8080
