apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../cluster

patches:
  - path: web-patch.yaml
    target:
      kind: Deployment
      name: montage-ai-web
  - path: worker-patch.yaml
    target:
      kind: Deployment
      name: montage-ai-worker
  - path: worker-heavy-patch.yaml
    target:
      kind: Deployment
      name: montage-ai-worker-heavy
