apiVersion: keda.sh/v1alpha1
kind: ScaledObject
metadata:
  name: montage-ai-worker-scaledobject
  labels:
    app.kubernetes.io/name: montage-ai
spec:
  scaleTargetRef:
    name: montage-ai-worker
  pollingInterval: 30
  cooldownPeriod: 120
  minReplicaCount: 1
  maxReplicaCount: 8
  triggers:
    - type: redis
      metadata:
        hostname: "<REDIS_HOST>"
        port: "<REDIS_PORT>"
        listName: "rq:queue:default"
        listLength: "10"
      authenticationRef: {}
