apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base

images:
  - name: ghcr.io/mfahsold/montage-ai
    newName: ghcr.io/mfahsold/montage-ai
    newTag: latest

patches:
  - path: patch-job-amd.yaml
